services:
  - type: web
    name: sql-server
    env: docker
    dockerfilePath: ./Lab3/Lab3/sql.Dockerfile
    envVars: []
    
  - type: web
    name: lab3
    env: docker
    dockerfilePath: ./Lab3/Lab3/Dockerfile
    envVars: :
      - key: PORT
        value: "7013:80"
