services:

  - type: web
    runtime: docker
    name: lab3
    dockerFile: Lab3/Lab3/Dockerfile
    numInstances: 1
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: ConnectionStrings_DefaultConnection  
        value: Server=sql-server;Database=Lab3DB;User=sa;Password=P@ssw0rd123;Encrypt=false
    deployType: container
    ports:
      - port: 80
        healthcheck: true

  - type: web
    runtime: docker
    name: sql-server
    dockerFile: Lab3/Lab3/sql.Dockerfile
    numInstances: 1
