services:
  - type: web
    name: sql-server
    env: docker
    dockerfile: ./Lab3/Lab3/sql.Dockerfile
    plan: free
    numInstances: 1
    autoDeploy: false
    healthCheckPath: /
  - type: web
    name: lab3
    env: docker
    dockerfile: ./Lab3/Lab3/Dockerfile
    plan: free
    numInstances: 1
    autoDeploy: false
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: ConnectionStrings__DefaultConnection
        value: Server=sql-server;Database=Lab3DB;User=sa;Password=P@ssw0rd123;Encrypt=false;
