version: '3'
services:
  lab3:
    container_name: lab3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7013:80" 
      - "5175:80"
    depends_on:
      - sql-server
  sql-server:
    container_name: sql-server
    build:
      context: .
      dockerfile: sql.Dockerfile