version: '3'
services:
  lab4:
    container_name: lab4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7090:80" 
      - "5025:80"
    depends_on:
      - postgresql-server
  postgresql-server:
    container_name: postgresql-server
    build:
      context: .
      dockerfile: sql.Dockerfile